added basic functionality
OspoWood/fileorganizer pull request #1
Opened 2023-10-28 11:26 UTC by OspoWood

2023-10-29 08:57 UTC, MrUndead1996 requested changes

2023-10-29 08:57 UTC, MrUndead1996 commented on src/main/java/com/ospo/fileorginizer/service/impl/FileSorterImpl.java
> +                    chunkGlossary.clear();
`chunkGlossary` лишний, тут счетчика достаточно + проверять что файл не кончился

2023-10-29 08:57 UTC, MrUndead1996 commented on src/test/java/com/ospo/fileorginizer/impl/FileSorterTest.java
> +        assertThat(countInput).isEqualTo(countOutput);
А проверить что файл отсортирован правильно?

2023-11-01 08:23 UTC, OspoWood commented on src/main/java/com/ospo/fileorginizer/service/impl/FileSorterImpl.java
> +                    chunkGlossary.clear();
chunkGlossary по логике не лишний, т.к. я на его основе создаю временный отсортированный файл, прошу поянить поточнее

2023-11-07 05:07 UTC, MrUndead1996 approved these changes

2023-11-07 11:31 UTC, OspoWood commented
add test

2023-11-07 11:31 UTC, merged